# Generated by Django 2.1.10 on 2019-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['user_name', 'create_datetime'], name='idx_user_name_create_datetime'),
        ),
    ]
