# Generated by Django 2.1.10 on 2019-12-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('p_price', models.IntegerField(verbose_name='价格')),
                ('p_unit', models.CharField(max_length=10, verbose_name='单位')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品管理',
                'db_table': 'server_product',
            },
        ),
    ]
